'use strict';
const C31=FoxesCommand;
const metrics31={pts:'Points',g:'Goals',a:'Assists',shots:'Shots',pm:'+/-',blocks:'Blocks',foPct:'FO%',toi:'TOI'};
let metric31='pts',teamMetric31='gf',trendPlayer31='',trendMetric31='pts';
const value31=(v,pct=false)=>v==null?'—':pct?(v*100).toFixed(1)+'%':Number(v).toFixed(1);
const game31=()=>state.savedGames.find(g=>g.id===state.currentGameId);
function cards31(items){return '<div class="snapshot313">'+items.map(([k,v])=>`<div class="metric313"><span>${esc(k)}</span><strong>${esc(v??'—')}</strong></div>`).join('')+'</div>';}
function chart31(rows,key,label){
 const known=rows.filter(r=>C31.valid(r[key]));if(!known.length)return '<p class="sub">No recorded data for this trend.</p>';
 const pct=['fo','pp','pk','foPct'].includes(key),fmt=v=>key==='toi'?formatSec(v):pct?(v*100).toFixed(0)+'%':Number(v).toFixed(1);
 const min=Math.min(0,...known.map(r=>Number(r[key]))),max=Math.max(pct?1:1,...known.map(r=>Number(r[key]))),x=i=>58+i*510/Math.max(1,rows.length-1),y=v=>130-(v-min)*104/(max-min);
 return `<svg class="trend31" viewBox="0 0 600 168" role="img" aria-label="${esc(label)}">${[min,(min+max)/2,max].map(v=>`<line x1="58" y1="${y(v)}" x2="568" y2="${y(v)}" stroke="#343b48"/><text x="48" y="${y(v)+4}" text-anchor="end" fill="#acb6c6" font-size="11">${fmt(v)}</text>`).join('')}${rows.map((r,i)=>C31.valid(r[key])?`${i&&C31.valid(rows[i-1][key])?`<line x1="${x(i-1)}" y1="${y(rows[i-1][key])}" x2="${x(i)}" y2="${y(r[key])}" stroke="#ef7188" stroke-width="2.5"/>`:''}<circle cx="${x(i)}" cy="${y(r[key])}" r="5" fill="#ef7188"><title>${esc(r.date||'Game')}: ${fmt(r[key])}</title></circle>`:'').join('')}<text x="58" y="157" fill="#acb6c6" font-size="11">${esc(rows[0]?.date||'First game')}</text><text x="568" y="157" text-anchor="end" fill="#acb6c6" font-size="11">${esc(rows.at(-1)?.date||'Latest game')}</text></svg><div class="trend-links31">${rows.map(r=>`<button data-game31="${esc(r.id)}">${esc(r.date||'Game')} · ${esc(r.opponent||'')}<br>${C31.valid(r[key])?fmt(r[key]):'—'}</button>`).join('')}</div>`;
}
function comparisonChart31(rows,keys,label){
 const known=rows.filter(r=>keys.some(k=>C31.valid(r[k])));if(!known.length)return '<p class="sub">No recorded data for this trend.</p>';
 const min=Math.min(0,...known.flatMap(r=>keys.filter(k=>C31.valid(r[k])).map(k=>Number(r[k])))),max=Math.max(1,...known.flatMap(r=>keys.filter(k=>C31.valid(r[k])).map(k=>Number(r[k])))),x=i=>58+i*510/Math.max(1,rows.length-1),y=v=>130-(v-min)*104/Math.max(1,max-min),colors=['#ef7188','#7fc7ff'];
 return `<svg class="trend31" viewBox="0 0 600 168" role="img" aria-label="${esc(label)}">${keys.map((key,ki)=>rows.map((r,i)=>C31.valid(r[key])?`${i&&C31.valid(rows[i-1][key])?`<line x1="${x(i-1)}" y1="${y(rows[i-1][key])}" x2="${x(i)}" y2="${y(r[key])}" stroke="${colors[ki]}" stroke-width="2.5"/>`:''}<circle cx="${x(i)}" cy="${y(r[key])}" r="4" fill="${colors[ki]}"><title>${esc(r.date||'Game')} ${esc(key)}: ${Number(r[key])}</title></circle>`:'').join('')).join('')}<text x="58" y="157" fill="#acb6c6" font-size="11">${esc(rows[0]?.date||'First game')}</text><text x="568" y="157" text-anchor="end" fill="#acb6c6" font-size="11">${esc(rows.at(-1)?.date||'Latest game')}</text></svg><div class="trend-legend31">${keys.map((key,i)=>`<span><i style="background:${colors[i]}"></i>${esc(key==='gf'?'Goals for':key==='ga'?'Goals against':key==='sf'?'Shots for':'Shots against')}</span>`).join('')}</div>`;
}
function options31(map,current){return Object.entries(map).map(([k,label])=>`<option value="${k}" ${k===current?'selected':''}>${esc(label)}</option>`).join('');}
const oldCommand31=renderCommand313;
let dashboardView318='overview';
function dashboardTabs318(){return `<div class="dashboard-tabs318" aria-label="Dashboard view"><button data-dashboard318="overview" aria-pressed="${dashboardView318==='overview'}">Game room</button><button data-dashboard318="jerseys" aria-pressed="${dashboardView318==='jerseys'}">Team jerseys</button></div>`;}
function renderJerseys318(root){
 const honors=A312.honors(state.savedGames||[],state.players,ratingConfig412()),lookup=new Map(honors.totals.map(t=>[String(t.p.number),t]));
 const roster=[...state.players].sort((a,b)=>Number(a.number)-Number(b.number));
 root.innerHTML=`<div class="jersey-heading318"><div><span class="eyebrow313">ARCTIC FOXES · SEASON HONORS</span><h1>The locker room</h1></div>${dashboardTabs318()}</div><div class="jersey-legend318"><span class="gold318">★ MVP / 1st</span><span class="silver318">★ 2nd</span><span class="bronze318">★ 3rd</span><span>SO · Recorded shutouts</span></div><div id="jerseyGrid318">${roster.map(p=>{const t=lookup.get(String(p.number))||{first:0,second:0,third:0,so:0};return `<button class="jersey-player318" data-profile-number="${esc(p.number)}" aria-label="${esc(p.name)}, number ${esc(p.number)}. MVP and first star ${t.first}, second star ${t.second}, third star ${t.third}${p.pos==='G'?`, shutouts ${t.so}`:''}. Open profile"><span class="jersey-shirt318" aria-hidden="true"><span class="jersey-name318">${esc(p.name)}</span><strong>${esc(p.number)}</strong><span class="jersey-awards318">${[['first','gold318'],['second','silver318'],['third','bronze318']].filter(([key])=>t[key]>0).map(([key,color])=>`<span class="${color}">★<b>${t[key]}</b></span>`).join('')}</span></span><span class="jersey-caption318">${esc(p.name)}${p.pos==='G'?` <small>G · ${t.so} SO</small>`:''}</span></button>`;}).join('')||'<p>Add players to your roster to fill the locker room.</p>'}</div>`;
 const grid=root.querySelector('#jerseyGrid318');
 const jerseys=[...grid.querySelectorAll('.jersey-player318')];
 if(jerseys.length){
  const positions=[['F','Forwards'],['D','Defensemen'],['G','Goalies']];
  if(roster.some(p=>!['F','D','G'].includes(p.pos)))positions.push(['other','Other positions']);
  positions.forEach(([pos,label])=>{
   const section=document.createElement('section');section.className='jersey-position319';section.setAttribute('aria-label',label);
   const players=roster.filter(p=>pos==='other'?!['F','D','G'].includes(p.pos):p.pos===pos);
   section.innerHTML=`<h2>${label} <small>${players.length}</small></h2><div class="jersey-position-grid319"></div>`;
   players.forEach(p=>{const jersey=jerseys.find(b=>b.dataset.profileNumber===String(p.number));if(jersey)section.lastElementChild.appendChild(jersey);});
   if(!players.length)section.lastElementChild.innerHTML='<span class="jersey-empty319">No players assigned</span>';
   grid.appendChild(section);
  });
 }
 requestAnimationFrame(fitJerseys318);
}
function fitJerseys318(){
 const grid=$('#jerseyGrid318');if(!grid||activeWorkspace!=='home'||dashboardView318!=='jerseys')return;
 const groups=[...grid.querySelectorAll('.jersey-position319')];if(!groups.length)return;
 const counts=groups.map(g=>g.querySelectorAll('.jersey-player318').length),width=grid.clientWidth,height=Math.max(240,window.innerHeight-grid.getBoundingClientRect().top-(window.innerWidth<=700?95:22));
 let best={size:0,cols:1,rows:counts.map(n=>Math.max(1,n))};
 for(let cols=1;cols<=Math.max(1,...counts);cols++){
  const rows=counts.map(n=>Math.max(1,Math.ceil(n/cols))),total=rows.reduce((a,b)=>a+b,0);
  const size=Math.min((width-(cols-1)*12)/cols/1.15,(height-groups.length*27-(total-1)*8)/total);
  if(size>best.size)best={size,cols,rows};
 }
 grid.style.gridTemplateColumns='1fr';grid.style.gridTemplateRows=best.rows.map(n=>`${27+n*best.size+(n-1)*8}px`).join(' ');grid.style.height=height+'px';
 groups.forEach((g,i)=>{g.lastElementChild.style.gridTemplateColumns=`repeat(${best.cols},minmax(0,1fr))`;g.lastElementChild.style.gridTemplateRows=`repeat(${best.rows[i]},minmax(0,1fr))`;});
 grid.style.setProperty('--jersey-size318',Math.max(30,best.size-25)+'px');
}
window.addEventListener('resize',fitJerseys318);
document.addEventListener('click',e=>{const b=e.target.closest('[data-dashboard318]');if(b){dashboardView318=b.dataset.dashboard318;renderCommand313();window.scrollTo(0,0);}});
renderCommand313=function(){
 document.body.classList.toggle('jersey-dashboard318',dashboardView318==='jerseys');
 if(dashboardView318==='jerseys'){renderJerseys318($('#commandCenter313'));return;}
 oldCommand31();const root=$('#commandCenter313'),d=C31.overview(state.savedGames||[],state.players);
 root.querySelector('.command-heading313').insertAdjacentHTML('beforeend',dashboardTabs318());
 root.querySelector('.snapshot313').outerHTML=cards31([['Record',d.record],['GF/G',value31(d.gf)],['GA/G',value31(d.ga)],['PP%',value31(d.pp,true)],['PK%',value31(d.pk,true)],['FO%',value31(d.fo,true)],['Shot differential / game',value31(d.diff)]]);
 const selectedGame=game31();
 if(selectedGame){const t=C31.team(selectedGame),score=t.gf!=null&&t.ga!=null?`${t.gf} – ${t.ga}`:'Score needed';root.querySelector('.command-heading313').insertAdjacentHTML('afterend',`<section class="game-focus315" aria-label="Selected game"><div><span class="eyebrow313">Selected game · ${esc(selectedGame.date||'Date not set')}</span><h2>vs ${esc(selectedGame.opponent||'Opponent')}</h2><span class="sub">${selectedGame.officialStats?.imported?'Official stats entered':'Stats not entered'} · ${(selectedGame.filmClips||[]).length} film clips</span></div><strong class="focus-score315">${score}</strong><div class="focus-actions315"><button class="primary313" data-ui-go313="film">Review film</button><button data-ui-go313="quickstats">Edit stats</button><button data-ui-go313="mygames">Game details</button></div></section>`);}
 root.querySelector('.snapshot313')?.classList.add('team-snapshot315');
 const honors=A312.honors(state.savedGames||[],state.players,ratingConfig412()),awards=honors.byGame.find(g=>g.id===selectedGame?.id)?.stars||[];
 const awardsPanel=`<section class="honors317" aria-label="Game stars"><h2>Game stars & MVP</h2><div class="honors-stars317">${awards.map(({r,place})=>`<article><span>${place===1?'★ MVP · 1st star':place===2?'★ 2nd star':'★ 3rd star'}</span>${player312(r)}<small>${r.type==='goalie'?`${r.saves} saves · ${r.ga} GA${r.so?' · Shutout':''}`:`${r.g} goals · ${r.a} assists · ${r.shots} shots`}</small></article>`).join('')||'<p>Save game stats to reveal the game stars.</p>'}</div><details><summary>Season honors · MVPs, stars & shutouts</summary>${table312(['Player','MVP / 1st','2nd','3rd','Shutouts'],honors.totals.filter(t=>t.mvp||t.second||t.third||t.p.pos==='G').sort((a,b)=>b.mvp-a.mvp||b.second-a.second||b.third-a.third).map(t=>row312([player312(t),t.mvp,t.second,t.third,t.p.pos==='G'?t.so:'—'])))}<p class="sub">Automatic awards use game MVP impact weights. MVP is the first star. Tied scores share a place; the next place is skipped. Shutouts come from recorded goalie SO stats.</p></details></section>`;
 (root.querySelector('.game-focus315')||root.querySelector('.command-heading313')).insertAdjacentHTML('afterend',awardsPanel);
 root.querySelector('.leaders313')?.previousElementSibling?.remove();root.querySelector('.leaders313')?.remove();
 const leaderSets=C31.leaderSets(d.rows),usageRows=C31.usage(d.rows),leaderLabels={points:'Points',goals:'Goals',assists:'Assists',rating:'Player rating',toi:'Recorded TOI',shots:'Shots',faceoffs:'Faceoff %',blocks:'Blocked shots'};
 const leaderCards=Object.entries(leaderLabels).map(([key,label])=>`<section class="leader-card319"><h3>${label}</h3>${key==='faceoffs'?'<p class="leader-note319">Minimum 10 attempts</p>':''}${leaderSets[key].length?table312(['Rank','Player','Value'],leaderSets[key].map(r=>row312([r.rank,player312({p:r.player}),key==='toi'?formatSec(r.value):value31(r.value,key==='faceoffs')]))):'<p class="leader-empty319">Unavailable or insufficient data</p>'}</section>`).join('');
 const selected=d.rows.find(r=>String(r.p.number)===trendPlayer31)||d.rows.find(r=>r.games.length);trendPlayer31=String(selected?.p.number??'');
 root.insertAdjacentHTML('beforeend',`<div class="command-report319"><section class="card leaders-report319"><h2>Team Leaders · Top 5</h2><p class="sub">Skaters only · recorded season data</p><div class="leader-grid319">${leaderCards}</div><button data-ui-go313="season">View all players</button></section><section class="card trend-report319"><h2>Team Performance Trends</h2><div class="trend-pair319">${comparisonChart31(d.trends,['gf','ga'],'Goals for and against by game')}${comparisonChart31(d.trends,['sf','sa'],'Shots for and against by game')}</div></section><section class="card usage-report319"><h2>Recorded TOI / Player Usage</h2><p class="sub">Confirmed or recorded TOI where available.</p>${usageRows.length?table312(['Rank','Player','TOI','Games','Avg/game'],usageRows.map(r=>row312([r.rank,player312({p:r.player}),formatSec(r.toi),r.games,formatSec(r.average)]))):'<p class="leader-empty319">Unavailable or insufficient data</p>'}</section><section class="card player-report319"><h2>Player Rating Trend</h2><label>Player <select id="trendPlayer31">${d.rows.filter(r=>r.games.length).map(r=>`<option value="${esc(r.p.number)}" ${String(r.p.number)===trendPlayer31?'selected':''}>#${esc(r.p.number)} ${esc(r.p.name)}</option>`).join('')}</select></label>${chart31(C31.playerTrend(selected,'rating'),'rating','Selected player rating')}</section><section class="card recent-report319"><h2>Recent Team Performance</h2><div class="recent-summary319"><strong>${esc(d.record??'Unavailable')}</strong><span>W–L–T</span><strong>${value31(d.gf)}</strong><span>GF/game</span><strong>${value31(d.ga)}</strong><span>GA/game</span></div>${d.last5.map(t=>`<button data-game31="${esc(t.id)}">${esc(t.date)} · ${esc(t.opponent)} · ${t.gf==null||t.ga==null?'Score unavailable':`${t.gf}–${t.ga}`}</button>`).join('')||'<p class="sub">No played games yet.</p>'}</section></div>`);
 // Place the analytical overview before history and secondary preparation.
 const report=root.querySelector('.command-report319');
 root.querySelector('.team-snapshot315').after(report);
 const preparation=root.querySelector('.next-game313');if(preparation)root.appendChild(preparation);
 root.querySelector('.command-heading313 h1').textContent='Game room';
 if(selectedGame){
  const t=C31.team(selectedGame),known=t.gf!=null&&t.ga!=null;
  root.querySelector('.game-focus315').innerHTML=`<div class="score-meta317">${known?(t.gf>t.ga?'WIN':t.gf<t.ga?'LOSS':'TIE'):'SCORE NEEDED'} · ${esc(selectedGame.date||'Date not set')}</div><div class="score-stage317"><div>ARCTIC FOXES<small>12U AA</small></div><strong>${t.gf??'—'} <span>–</span> ${t.ga??'—'}</strong><div>${esc(selectedGame.opponent||'Opponent')}<small>Selected game</small></div></div><div class="periods317">${['p1','p2','p3','ot'].map((p,i)=>`<span>${['1ST','2ND','3RD','OT'][i]} &nbsp; ${t.gf!=null?(t.raw.goalsFor?.[p]??'—'):'—'}–${t.ga!=null?(t.raw.goalsAgainst?.[p]??'—'):'—'}</span>`).join('')}</div><div class="focus-actions315"><button class="primary313" data-ui-go313="film">Review film</button><button data-ui-go313="quickstats">Edit stats</button><button data-ui-go313="mygames">Game details</button></div>`;
  const comparisons=[['Shots on goal',t.sf,t.sa],['Goals',t.gf,t.ga],['Faceoffs won',t.raw.fow,t.raw.fol]];
  report.insertAdjacentHTML('afterbegin',`<section class="card game-comparison317"><h2>Game comparison</h2>${comparisons.map(([label,a,b])=>{const valid= C31.valid(a)&&C31.valid(b),total=Number(a)+Number(b);return `<div class="comparison317"><div><span>${label}</span><strong>${valid?`${a} / ${b}`:'Not recorded'}</strong></div>${valid&&total>0?`<div class="comparison-track317" role="img" aria-label="${label}: Foxes ${a}, opponent ${b}"><i style="width:${Math.max(0,Math.min(100,100*Number(a)/total))}%"></i></div>`:''}</div>`;}).join('')}<small>Foxes / ${esc(selectedGame.opponent||'Opponent')}</small></section>`);
 }
 root.querySelector('.command-heading313 p').textContent='Game results, season performance, and the next coaching decision.';
 $('#trendPlayer31').onchange=e=>{trendPlayer31=e.target.value;renderCommand313();};
};
updateCoach312=renderCommand313;
function timeline31(g){const rows=C31.intervals(g);return `<h3>Shift Timeline</h3><p>Confirmed intervals only. Click a shift to seek its source clip. Legacy shifts without video anchors remain in the Shift Log.</p>${(g.filmClips||[]).map(clip=>{const s=rows.filter(s=>s.startClipId===clip.id),end=Math.max(1,clip.duration||0,...s.map(s=>s.videoOffTime));return `<h4>${esc(clip.name||clip.label||'Clip')} · ${formatSec(end)}</h4>${(g.players||[]).map(p=>`<div class="timeline-row31"><span>#${esc(p.number)} ${esc(p.name)}</span><div class="timeline-track31">${s.filter(s=>s.playerId===p.id).map(s=>`<button class="shift31" style="left:${100*s.videoOnTime/end}%;width:${Math.max(.3,100*(s.videoOffTime-s.videoOnTime)/end)}%" data-seek31="${s.videoOnTime}" data-clip31="${esc(clip.id)}" title="${esc(p.name)} ${stamp314(s.videoOnTime)}–${stamp314(s.videoOffTime)}" aria-label="Seek ${esc(p.name)} shift at ${stamp314(s.videoOnTime)}"></button>`).join('')}</div></div>`).join('')}`;}).join('')||'<p>Add film and record video shifts first.</p>'}`;}
function quality31(g){const q=C31.quality(g);return cards31([['Roster/stat matches',`${q.matched}/${q.roster}`],['Stats imported',q.stats?'Yes':'Needed'],['Goalie summaries',q.goalies||'Needed'],['TOI',q.toi?'Finalized':'Review needed'],['Unknown Auto Tracks',q.unknown],['Questionable crossings',q.questionable],['Open / unconfirmed shifts',q.open],['Shifts without video anchors',q.missingVideo],['Report readiness',q.ready?'Ready':'Review required']])+`<button data-ui-go313="film">Review tracking & finalize TOI</button>`;}
function notes31(g){const notes=g.command31?.notes||{};return `<h3>Private Coach Notes</h3><p>Saved locally with your season; excluded from the game report. Season backups include these notes.</p><label>Notes for <select id="noteTarget31"><option value="game">This game</option>${(g.players||[]).map(p=>`<option value="${esc(p.id)}">#${esc(p.number)} ${esc(p.name)}</option>`).join('')}</select></label><div id="noteFields31"></div><button id="saveNotes31">Save Notes</button>`;}
function mountNotes31(g){const fill=()=>{const n=state.command31?.notes?.[$('#noteTarget31').value]||{};$('#noteFields31').innerHTML=['Strengths','Needs Work','Current Focus','Film Notes'].map(k=>`<label class="note31">${k}<textarea data-note31="${k}">${esc(n[k]||'')}</textarea></label>`).join('');};fill();$('#noteTarget31').onchange=fill;$('#saveNotes31').onclick=()=>{snapshot();const c=state.command31||(state.command31={});c.notes=c.notes||{};c.notes[$('#noteTarget31').value]=Object.fromEntries([...document.querySelectorAll('[data-note31]')].map(e=>[e.dataset.note31,e.value]));save();$('#saveNotes31').textContent='Notes saved';};}
function bookmarks31(g){return `<h3>Film bookmarks</h3>${table312(['Tag','Association','Video'],(g.command31?.bookmarks||[]).map(b=>row312([esc(b.tag),esc(b.playerName||'Team'),`<button data-seek31="${b.time}" data-clip31="${esc(b.clipId)}">${stamp314(b.time)}</button>`])))}<button data-ui-go313="film">Add bookmarks in Film</button>`;}
const oldTab31=gameTab312;
gameTab312=function(tab){
 const g=game31(),m=$('#gameDetail312');if(!g||!m)return oldTab31(tab);
 if(!['overview','timeline','lines','notes','quality','clips','gameday'].includes(tab))return oldTab31(tab);
 gameView313=tab;const t=C31.team(g),r=A312.records(g).filter(r=>r.played);
 if(tab==='overview')m.innerHTML=`<h2>FOXES ${t.gf??'—'} — ${esc(g.opponent)} ${t.ga??'—'}</h2>${cards31([['PP%',value31(t.pp,true)],['PK%',value31(t.pk,true)],['FO%',value31(t.fo,true)]])}${table312(['Period totals','1st','2nd','3rd','OT','Total'],['goalsFor','goalsAgainst','shotsFor','shotsAgainst'].map(k=>row312([esc(k.replace(/([A-Z])/g,' $1')),...['p1','p2','p3','ot','total'].map(p=>g.officialStats?.imported?(t.raw[k]?.[p]??'—'):'—')])))}<div class="grid31"><section><h3>Top performers · points</h3>${table312(['Player','PTS'],r.filter(r=>r.type==='skater').sort((a,b)=>b.pts-a.pts).slice(0,3).map(r=>row312([player312(r),r.pts])))}</section><section><h3>TOI leaders</h3>${table312(['Player','TOI'],T314.summary(g,null,null,true).filter(r=>r.total>0).slice(0,5).map(r=>row312([esc('#'+r.player.number+' '+r.player.name),formatSec(r.total)])))}</section></div><h3>Goalies</h3>${table312(['Player','Saves','GA','SV%','MIN'],r.filter(r=>r.type==='goalie').map(r=>row312([player312(r),r.saves,r.ga,value31(C31.ratio(r.saves,r.sa),true),r.min])))}<details><summary>Data Quality Center</summary>${quality31(g)}</details>`;
 if(tab==='timeline')m.innerHTML=timeline31(g);
 if(tab==='lines')m.innerHTML='<h3>Line & D-Pair Usage</h3><p>Confirmed video overlap, grouped by clip. Exact forward trios and defense pairs; extra-player intervals are excluded. GF/GA, shots and chances together are not yet attributed.</p>'+table312(['Unit','Players','Time together'],C31.overlaps(g).map(r=>row312([r.pos==='F'?'Forward line':'D-pair',esc(r.players.map(p=>'#'+p.jerseyNumber+' '+p.playerName).join(' · ')),formatSec(r.seconds)])));
 if(tab==='quality')m.innerHTML='<h3>Data Quality Center</h3>'+quality31(g)+`<details><summary>Tracking correction history</summary>${table312(['When','Player','Before','After'],(g.toi314?.audit||[]).flatMap(a=>a.changes.map(c=>row312([esc(new Date(a.at).toLocaleString()),esc((c.after||c.before)?.playerName||'Player'),c.before?stamp314(c.before.videoOnTime)+' – '+stamp314(c.before.videoOffTime):'Added',c.after?stamp314(c.after.videoOnTime)+' – '+stamp314(c.after.videoOffTime):'Deleted']))))}<p>${(g.toi314?.groundTruth||[]).length} saved review/correction evidence entries.</p><p>Use Undo Tracking in Film to restore a recent correction.</p></details>`;
 if(tab==='notes'){m.innerHTML=notes31(g);mountNotes31(g);}
 if(tab==='clips')m.innerHTML=bookmarks31(g);
 if(tab==='gameday'){const p=g.command31?.pregame||{};m.innerHTML=`<h3>Pregame · ${esc(g.opponent)}</h3>${['Scout','Game Plan','Lines','Starting Goalie'].map(k=>`<label class="note31">${k}<textarea data-plan31="${k}">${esc(p[k]||'')}</textarea></label>`).join('')}<button id="savePlan31">Save Game Plan</button><h3>Postgame</h3><div class="row">${[['stats','Import Stats'],['film','Add Film / Track TOI / Review Unknowns']].map(([k,v])=>`<button data-ui-go313="${k}">${v}</button>`).join('')}<button data-tab31="quality">Finalize readiness</button><button data-tab31="report">Game Report</button></div>${quality31(g)}`;$('#savePlan31').onclick=()=>{snapshot();state.command31=state.command31||{};state.command31.pregame=Object.fromEntries([...document.querySelectorAll('[data-plan31]')].map(e=>[e.dataset.plan31,e.value]));save();$('#savePlan31').textContent='Game plan saved';};}
};
const oldHub31=renderGameHub312;
renderGameHub312=function(){oldHub31();const tabs=$('#gameHub312 .game-tabs313');if(tabs)tabs.insertAdjacentHTML('beforeend',`<details><summary>More game tools</summary>${[['gameday','Game Day'],['timeline','Shift Timeline'],['lines','Lines & D-Pairs'],['clips','Clips'],['notes','Coach Notes'],['quality','Data Quality']].map(([k,v])=>`<button data-tab31="${k}">${v}</button>`).join('')}</details>`);};
document.addEventListener('click',e=>{const g=e.target.closest('[data-game31],[data-open-game313]');if(g){if(g.dataset.game31)loadSavedGame(g.dataset.game31);openWorkspace('mygames');}const b=e.target.closest('[data-tab31]');if(b)gameTab312(b.dataset.tab31);const s=e.target.closest('[data-seek31]');if(s){openWorkspace('film');jump314(s.dataset.clip31,Number(s.dataset.seek31));}});
function playerHonors317(number){const t=A312.honors(state.savedGames||[],state.players,ratingConfig412()).totals.find(t=>String(t.p.number)===String(number));return t?`<section class="player-honors317"><h3>Season honors</h3>${cards31([['MVP / 1st star',t.mvp],['2nd star',t.second],['3rd star',t.third],...(t.p.pos==='G'?[['Shutouts',t.so]]:[])])}<small>MVP counts as first star · recorded goalie shutouts</small></section>`:'';}
const baseHonorsDevelop317=renderPlayerValuePage;
renderPlayerValuePage=function(){baseHonorsDevelop317();if(ratingSelected31)$('#ratingFocus').insertAdjacentHTML('beforeend',playerHonors317(ratingSelected31));};
const baseHonorsProfile317=renderPlayerProfile;
renderPlayerProfile=function(){baseHonorsProfile317();$('#playerProfilePage .player-honors317')?.remove();$('#profileValue')?.parentElement.insertAdjacentHTML('afterend',playerHonors317(activeProfileNumber));};
// Additive saved-game fields use the same snapshot and Undo pipeline as existing tracking.
const oldSnapshot31=currentGameSnapshot;currentGameSnapshot=function(){return {...oldSnapshot31(),command31:deepClone(state.command31||{})};};
const oldLoad31=loadSavedGame;loadSavedGame=function(id){const g=state.savedGames.find(g=>g.id===id);if(g)state.command31=deepClone(g.command31||{});return oldLoad31(id);};
const oldCreate31=createSimpleGame;createSimpleGame=function(){state.command31={};return oldCreate31();};
state.command31=deepClone(game31()?.command31||state.command31||{});
renderCommand313();renderGameHub312();
