'use strict';
const C31=FoxesCommand;
const metrics31={pts:'Points',g:'Goals',a:'Assists',shots:'Shots',pm:'+/-',blocks:'Blocks',foPct:'FO%',toi:'TOI'};
let metric31='pts',teamMetric31='gf',trendPlayer31='',trendMetric31='pts';
const value31=(v,pct=false)=>v==null?'—':pct?(v*100).toFixed(1)+'%':Number(v).toFixed(1);
const game31=()=>state.savedGames.find(g=>g.id===state.currentGameId);
function cards31(items){return '<div class="snapshot313">'+items.map(([k,v])=>`<div class="metric313"><span>${esc(k)}</span><strong>${esc(v??'—')}</strong></div>`).join('')+'</div>';}
function chart31(rows,key,label){
 const known=rows.filter(r=>C31.valid(r[key]));if(!known.length)return '<p class="sub">No recorded data for this trend.</p>';
 const min=Math.min(0,...known.map(r=>Number(r[key]))),max=Math.max(1,...known.map(r=>Number(r[key]))),x=i=>25+i*550/Math.max(1,rows.length-1),y=v=>125-(v-min)*100/(max-min);
 return `<svg class="trend31" viewBox="0 0 600 150" role="img" aria-label="${esc(label)}"><path d="M25 10V125H580" fill="none" stroke="#64748b"/>${rows.map((r,i)=>C31.valid(r[key])?`${i&&C31.valid(rows[i-1][key])?`<line x1="${x(i-1)}" y1="${y(rows[i-1][key])}" x2="${x(i)}" y2="${y(r[key])}" stroke="#ef7188" stroke-width="2"/>`:''}<circle cx="${x(i)}" cy="${y(r[key])}" r="5" fill="#ef7188"/>`:'').join('')}</svg><div class="trend-links31">${rows.map(r=>`<button data-game31="${esc(r.id)}">${esc(r.date||'Game')} · ${esc(r.opponent||'')}<br>${value31(r[key],['fo','pp','pk','foPct'].includes(key))}</button>`).join('')}</div>`;
}
function options31(map,current){return Object.entries(map).map(([k,label])=>`<option value="${k}" ${k===current?'selected':''}>${esc(label)}</option>`).join('');}
const oldCommand31=renderCommand313;
renderCommand313=function(){
 oldCommand31();const root=$('#commandCenter313'),d=C31.overview(state.savedGames||[],state.players);
 root.querySelector('.snapshot313').outerHTML=cards31([['Record',d.record],['GF/G',value31(d.gf)],['GA/G',value31(d.ga)],['PP%',value31(d.pp,true)],['PK%',value31(d.pk,true)],['FO%',value31(d.fo,true)],['Shot differential / game',value31(d.diff)]]);
 root.querySelector('.leaders313')?.previousElementSibling?.remove();root.querySelector('.leaders313')?.remove();
 const rows=d.rows.filter(r=>r.type==='skater'&&r.games.length&&(metric31!=='foPct'||r.fo>0)&&(metric31!=='toi'||r.toi>0)).sort((a,b)=>b[metric31]-a[metric31]).slice(0,5);
 const selected=d.rows.find(r=>String(r.p.number)===trendPlayer31)||d.rows.find(r=>r.games.length);trendPlayer31=String(selected?.p.number??'');
 root.insertAdjacentHTML('beforeend',`<div class="grid31"><section class="card"><h2>Top 5</h2><label>Category <select id="leaderMetric31">${options31(metrics31,metric31)}</select></label>${table312(['Player',metrics31[metric31]],rows.map(r=>row312([player312(r),metric31==='toi'?formatSec(r.toi):value31(r[metric31],metric31==='foPct')])))}<button data-ui-go313="season">View all players</button></section><section class="card"><h2>Last 5 played games</h2>${d.last5.map(t=>`<button data-game31="${esc(t.id)}">${esc(t.date)} · ${esc(t.opponent)} · ${t.gf==null||t.ga==null?'Score unavailable':`${t.gf}–${t.ga}`}</button>`).join('')||'<p>No played games yet.</p>'}<p>Season GF/G ${value31(d.gf)} · Last 5 GF/G ${value31(C31.overview((state.savedGames||[]).filter(g=>d.last5.some(t=>t.id===g.id)),state.players).gf)}</p></section><section class="card"><h2>Team trend</h2><label>Metric <select id="teamMetric31">${options31({gf:'Goals for',ga:'Goals against',sf:'Shots for',sa:'Shots against',diff:'Shot differential',fo:'FO%',pp:'PP%',pk:'PK%'},teamMetric31)}</select></label>${chart31(d.trends,teamMetric31,'Team trend')}</section><section class="card"><h2>Player trend</h2><label>Player <select id="trendPlayer31">${d.rows.filter(r=>r.games.length).map(r=>`<option value="${esc(r.p.number)}" ${String(r.p.number)===trendPlayer31?'selected':''}>#${esc(r.p.number)} ${esc(r.p.name)}</option>`).join('')}</select></label><label>Metric <select id="trendMetric31">${options31(metrics31,trendMetric31)}</select></label>${chart31((selected?.games||[]).map(g=>({...g.record,...g,foPct:C31.ratio(g.record.fow,g.record.fo)})),trendMetric31,'Player trend')}</section></div>`);
 for(const [id,set] of [['leaderMetric31',v=>metric31=v],['teamMetric31',v=>teamMetric31=v],['trendPlayer31',v=>trendPlayer31=v],['trendMetric31',v=>trendMetric31=v]])$('#'+id).onchange=e=>{set(e.target.value);renderCommand313();};
};
updateCoach312=renderCommand313;
function timeline31(g){const rows=C31.intervals(g);return `<h3>Shift Timeline</h3><p>Confirmed intervals only. Click a shift to seek its source clip. Legacy shifts without video anchors remain in the Shift Log.</p>${(g.filmClips||[]).map(clip=>{const s=rows.filter(s=>s.startClipId===clip.id),end=Math.max(1,clip.duration||0,...s.map(s=>s.videoOffTime));return `<h4>${esc(clip.name||clip.label||'Clip')} · ${formatSec(end)}</h4>${(g.players||[]).map(p=>`<div class="timeline-row31"><span>#${esc(p.number)} ${esc(p.name)}</span><div class="timeline-track31">${s.filter(s=>s.playerId===p.id).map(s=>`<button class="shift31" style="left:${100*s.videoOnTime/end}%;width:${Math.max(.3,100*(s.videoOffTime-s.videoOnTime)/end)}%" data-seek31="${s.videoOnTime}" data-clip31="${esc(clip.id)}" title="${esc(p.name)} ${stamp314(s.videoOnTime)}–${stamp314(s.videoOffTime)}" aria-label="Seek ${esc(p.name)} shift at ${stamp314(s.videoOnTime)}"></button>`).join('')}</div></div>`).join('')}`;}).join('')||'<p>Add film and record video shifts first.</p>'}`;}
function quality31(g){const q=C31.quality(g);return cards31([['Roster/stat matches',`${q.matched}/${q.roster}`],['Stats imported',q.stats?'Yes':'Needed'],['Goalie summaries',q.goalies||'Needed'],['TOI',q.toi?'Finalized':'Review needed'],['Unknown Auto Tracks',q.unknown],['Questionable crossings',q.questionable],['Open / unconfirmed shifts',q.open],['Shifts without video anchors',q.missingVideo],['Report readiness',q.ready?'Ready':'Review required']])+`<button data-ui-go313="film">Review tracking & finalize TOI</button>`;}
function notes31(g){const notes=g.command31?.notes||{};return `<h3>Private Coach Notes</h3><p>Saved locally with your season; excluded from the game report. Season backups include these notes.</p><label>Notes for <select id="noteTarget31"><option value="game">This game</option>${(g.players||[]).map(p=>`<option value="${esc(p.id)}">#${esc(p.number)} ${esc(p.name)}</option>`).join('')}</select></label><div id="noteFields31"></div><button id="saveNotes31">Save Notes</button>`;}
function mountNotes31(g){const fill=()=>{const n=state.command31?.notes?.[$('#noteTarget31').value]||{};$('#noteFields31').innerHTML=['Strengths','Needs Work','Current Focus','Film Notes'].map(k=>`<label class="note31">${k}<textarea data-note31="${k}">${esc(n[k]||'')}</textarea></label>`).join('');};fill();$('#noteTarget31').onchange=fill;$('#saveNotes31').onclick=()=>{snapshot();const c=state.command31||(state.command31={});c.notes=c.notes||{};c.notes[$('#noteTarget31').value]=Object.fromEntries([...document.querySelectorAll('[data-note31]')].map(e=>[e.dataset.note31,e.value]));save();$('#saveNotes31').textContent='Notes saved';};}
function bookmarks31(g){return `<h3>Film bookmarks</h3>${table312(['Tag','Association','Video'],(g.command31?.bookmarks||[]).map(b=>row312([esc(b.tag),esc(b.playerName||'Team'),`<button data-seek31="${b.time}" data-clip31="${esc(b.clipId)}">${stamp314(b.time)}</button>`])))}<button data-ui-go313="film">Add bookmarks in Film</button>`;}
const oldTab31=gameTab312;
gameTab312=function(tab){
 const g=game31(),m=$('#gameDetail312');if(!g||!m)return oldTab31(tab);
 if(!['overview','timeline','lines','notes','quality','clips','gameday'].includes(tab))return oldTab31(tab);
 gameView313=tab;const t=C31.team(g),r=A312.records(g).filter(r=>r.played);
 if(tab==='overview')m.innerHTML=`<h2>FOXES ${t.gf??'—'} — ${esc(g.opponent)} ${t.ga??'—'}</h2>${cards31([['PP%',value31(t.pp,true)],['PK%',value31(t.pk,true)],['FO%',value31(t.fo,true)]])}${table312(['Period totals','1st','2nd','3rd','OT','Total'],['goalsFor','goalsAgainst','shotsFor','shotsAgainst'].map(k=>row312([esc(k.replace(/([A-Z])/g,' $1')),...['p1','p2','p3','ot','total'].map(p=>g.officialStats?.imported?(t.raw[k]?.[p]??'—'):'—')])))}<div class="grid31"><section><h3>Top performers · points</h3>${table312(['Player','PTS'],r.filter(r=>r.type==='skater').sort((a,b)=>b.pts-a.pts).slice(0,3).map(r=>row312([player312(r),r.pts])))}</section><section><h3>TOI leaders</h3>${table312(['Player','TOI'],T314.summary(g,null,null,true).filter(r=>r.total>0).slice(0,5).map(r=>row312([esc('#'+r.player.number+' '+r.player.name),formatSec(r.total)])))}</section></div><h3>Goalies</h3>${table312(['Player','Saves','GA','SV%','MIN'],r.filter(r=>r.type==='goalie').map(r=>row312([player312(r),r.saves,r.ga,value31(C31.ratio(r.saves,r.sa),true),r.min])))}<details><summary>Data Quality Center</summary>${quality31(g)}</details>`;
 if(tab==='timeline')m.innerHTML=timeline31(g);
 if(tab==='lines')m.innerHTML='<h3>Line & D-Pair Usage</h3><p>Confirmed video overlap, grouped by clip. Exact forward trios and defense pairs; extra-player intervals are excluded. GF/GA, shots and chances together are not yet attributed.</p>'+table312(['Unit','Players','Time together'],C31.overlaps(g).map(r=>row312([r.pos==='F'?'Forward line':'D-pair',esc(r.players.map(p=>'#'+p.jerseyNumber+' '+p.playerName).join(' · ')),formatSec(r.seconds)])));
 if(tab==='quality')m.innerHTML='<h3>Data Quality Center</h3>'+quality31(g)+`<details><summary>Tracking correction history</summary>${table312(['When','Player','Before','After'],(g.toi314?.audit||[]).flatMap(a=>a.changes.map(c=>row312([esc(new Date(a.at).toLocaleString()),esc((c.after||c.before)?.playerName||'Player'),c.before?stamp314(c.before.videoOnTime)+' – '+stamp314(c.before.videoOffTime):'Added',c.after?stamp314(c.after.videoOnTime)+' – '+stamp314(c.after.videoOffTime):'Deleted']))))}<p>${(g.toi314?.groundTruth||[]).length} saved review/correction evidence entries.</p><p>Use Undo Tracking in Film to restore a recent correction.</p></details>`;
 if(tab==='notes'){m.innerHTML=notes31(g);mountNotes31(g);}
 if(tab==='clips')m.innerHTML=bookmarks31(g);
 if(tab==='gameday'){const p=g.command31?.pregame||{};m.innerHTML=`<h3>Pregame · ${esc(g.opponent)}</h3>${['Scout','Game Plan','Lines','Starting Goalie'].map(k=>`<label class="note31">${k}<textarea data-plan31="${k}">${esc(p[k]||'')}</textarea></label>`).join('')}<button id="savePlan31">Save Game Plan</button><h3>Postgame</h3><div class="row">${[['stats','Import Stats'],['film','Add Film / Track TOI / Review Unknowns']].map(([k,v])=>`<button data-ui-go313="${k}">${v}</button>`).join('')}<button data-tab31="quality">Finalize readiness</button><button data-tab31="report">Game Report</button></div>${quality31(g)}`;$('#savePlan31').onclick=()=>{snapshot();state.command31=state.command31||{};state.command31.pregame=Object.fromEntries([...document.querySelectorAll('[data-plan31]')].map(e=>[e.dataset.plan31,e.value]));save();$('#savePlan31').textContent='Game plan saved';};}
};
const oldHub31=renderGameHub312;
renderGameHub312=function(){oldHub31();const tabs=$('#gameHub312 .game-tabs313');if(tabs)tabs.insertAdjacentHTML('beforeend',`<details><summary>More game tools</summary>${[['gameday','Game Day'],['timeline','Shift Timeline'],['lines','Lines & D-Pairs'],['clips','Clips'],['notes','Coach Notes'],['quality','Data Quality']].map(([k,v])=>`<button data-tab31="${k}">${v}</button>`).join('')}</details>`);};
document.addEventListener('click',e=>{const g=e.target.closest('[data-game31],[data-open-game313]');if(g){if(g.dataset.game31)loadSavedGame(g.dataset.game31);openWorkspace('mygames');}const b=e.target.closest('[data-tab31]');if(b)gameTab312(b.dataset.tab31);const s=e.target.closest('[data-seek31]');if(s){openWorkspace('film');jump314(s.dataset.clip31,Number(s.dataset.seek31));}});
// Additive saved-game fields use the same snapshot and Undo pipeline as existing tracking.
const oldSnapshot31=currentGameSnapshot;currentGameSnapshot=function(){return {...oldSnapshot31(),command31:deepClone(state.command31||{})};};
const oldLoad31=loadSavedGame;loadSavedGame=function(id){const g=state.savedGames.find(g=>g.id===id);if(g)state.command31=deepClone(g.command31||{});return oldLoad31(id);};
const oldCreate31=createSimpleGame;createSimpleGame=function(){state.command31={};return oldCreate31();};
state.command31=deepClone(game31()?.command31||state.command31||{});
renderCommand313();renderGameHub312();
