'use strict';
const OP320=FoxesOpponent;
let opponentDraft320=null,opponentRead320=0;
const opponentMount320=document.createElement('section');opponentMount320.className='card opponent-sheet320';
document.querySelector('[data-workspace-page="scout"]').prepend(opponentMount320);
function opponentRows320(rows){return rows.map(p=>`<tr>${['number','name','g','a','pts','pim','penalties'].map(k=>`<td><input aria-label="${esc(k==='number'?'Jersey number':k)}" data-op-field320="${k}" value="${esc(p[k]??'')}" ${!['number','name'].includes(k)?'inputmode="numeric"':''}></td>`).join('')}<td><button type="button" data-op-remove320>Remove</button></td></tr>`).join('');}
function mountOpponent320(){
 const g=game31(),sheet=g?.command31?.opponentSheet;
 opponentMount320.innerHTML=`<h2>Opponent scoresheet</h2><p class="sub">${g?`${esc(g.date||'No date')} · ${esc(g.opponent||'No opponent')}`:'Open a game in My Games to attach its opponent scoresheet.'}</p>${g?`<p>Upload a clear screenshot of the <strong>opponent player-stat table</strong>. Review the names and numbers before saving. Goal-event sheets and handwriting may need manual entry.</p><div class="row"><label class="file-label">Add photo / screenshot<input id="opPhoto320" type="file" accept="image/png,image/jpeg" hidden></label><button id="opManual320">${sheet?'Edit saved player stats':'Enter stats manually'}</button></div><p id="opStatus320" role="status"></p><div id="opDraft320"></div>${sheet?`<details><summary>Saved scoresheet · ${esc(sheet.sourceName||'Manual entry')} · ${sheet.players.length} players</summary>${sheet.image?'<img class="op-photo320" id="opSavedImage320" alt="Saved opponent scoresheet">':''}${table312(['#','Opponent player','G','A','PTS','PIM','Penalties'],sheet.players.map(p=>row312([esc(p.number),esc(p.name),p.g??'—',p.a??'—',p.pts??'—',p.pim??'—',p.penalties??'—'])))}</details>`:''}`:''}<div id="opHistory320"></div>`;
 if(sheet?.image?.startsWith('data:image/png;base64,'))$('#opSavedImage320').src=sheet.image;
 if(g){$('#opPhoto320').onchange=readOpponentPhoto320;$('#opManual320').onclick=()=>{opponentRead320++;opponentDraft320={gameId:g.id,opponent:g.opponent,base:JSON.stringify(g.command31?.opponentSheet||null),sourceName:sheet?.sourceName||'Manual entry',image:sheet?.image||'',rows:sheet?.players||[{number:'',name:'',g:'',a:'',pts:''}]};showOpponentDraft320();};}
 renderOpponentHistory320();
}
async function readOpponentPhoto320(e){
 const file=e.target.files?.[0],g=game31();if(!file||!g)return;const token=++opponentRead320;
 opponentDraft320=null;$('#opDraft320').innerHTML='';$('#opStatus320').textContent='Reading the photo…';
 try{if(!window.foxesStorage?.readOpponentPhoto)throw Error('Photo reading is available in the updated desktop app.');if(file.size>12*1024*1024)throw Error('Choose a photo smaller than 12 MB.');
 const base=JSON.stringify(g.command31?.opponentSheet||null),result=await window.foxesStorage.readOpponentPhoto(new Uint8Array(await file.arrayBuffer()));
 if(token!==opponentRead320||state.currentGameId!==g.id||game31()?.opponent!==g.opponent)return;
 const rows=OP320.readPhoto(result.words);opponentDraft320={gameId:g.id,opponent:g.opponent,base,sourceName:file.name,image:result.image,text:result.text,rows:rows.length?rows:[{number:'',name:'',g:'',a:'',pts:''}]};showOpponentDraft320();
 $('#opStatus320').textContent=rows.length?`Read ${rows.length} possible player rows. Check every value against the image.`:'No player table recognized. The photo is attached below; enter the opponent stats before saving.';
 }catch(err){if(token===opponentRead320&&state.currentGameId===g.id)$('#opStatus320').textContent=err.message;}
}
function showOpponentDraft320(){const d=opponentDraft320;if(!d)return;
 $('#opDraft320').innerHTML=`<h3>Review opponent stats · ${esc(d.opponent)}</h3><p>Keep only this opponent's players. Blank stats stay unknown. Saving replaces this game's opponent stats.</p>${d.image?'<details open><summary>Check uploaded photo</summary><img class="op-photo320" id="opDraftImage320" alt="Opponent scoresheet to review"></details>':''}<div class="table-wrap313"><table><thead><tr>${['#','Player name','G','A','PTS','PIM','Penalties',''].map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody id="opRows320">${opponentRows320(d.rows)}</tbody></table></div><div class="row"><button id="opAdd320">Add player</button><button id="opSave320" class="primary313">Save opponent scoresheet</button><button id="opCancel320">Cancel</button></div>${d.text?`<details><summary>Text read from photo</summary><pre>${esc(d.text)}</pre></details>`:''}`;
 if(d.image)$('#opDraftImage320').src=d.image;
 $('#opRows320').onclick=e=>{if(e.target.closest('[data-op-remove320]'))e.target.closest('tr').remove();};
 $('#opAdd320').onclick=()=>$('#opRows320').insertAdjacentHTML('beforeend',opponentRows320([{}]));
 $('#opCancel320').onclick=()=>{opponentDraft320=null;opponentRead320++;mountOpponent320();};
 $('#opSave320').onclick=()=>{try{const g=game31();if(g?.id!==d.gameId||g.opponent!==d.opponent||JSON.stringify(g.command31?.opponentSheet||null)!==d.base)throw Error('The game or scoresheet changed. Open the import again.');if(!g.opponent?.trim())throw Error('Set the opponent name in My Games first.');
 const rows=[...$('#opRows320').children].map(tr=>Object.fromEntries([...tr.querySelectorAll('input')].map(i=>[i.dataset.opField320,i.value]))),players=OP320.validate(rows);
 snapshot();state.command31=state.command31||{};state.command31.opponentSheet={opponent:g.opponent,sourceName:d.sourceName,image:d.image,players,updatedAt:new Date().toISOString()};save();opponentDraft320=null;mountOpponent320();$('#opStatus320').textContent='Opponent scoresheet saved.';renderCommand313();
 }catch(err){$('#opStatus320').textContent=err.message;}};
}
function opponentReminder320(opponent,date,excludeId){const h=OP320.history(state.savedGames||[],opponent,date,excludeId);if(!h.latest)return '';
 const penalties=h.latest.command31.opponentSheet.players.filter(p=>p.pim>=4||p.penalties>=2);
 return `<section class="op-reminder320"><h3>Opponent watch · ${esc(opponent)}</h3>${h.alerts.length?h.alerts.map(p=>`<p><strong>#${esc(p.number)} ${esc(p.name)}</strong> had <strong>${p.pts} points</strong> against us on ${esc(h.latest.date)}${h.lastMeeting?.id===h.latest.id?' · last meeting': ' · latest scoresheet on file'}.</p>`).join(''):`<p>Player stats available from ${esc(h.latest.date)}.</p>`}${penalties.map(p=>`<p><strong>#${esc(p.number)} ${esc(p.name)}</strong> recorded ${p.pim!=null?`${p.pim} penalty minutes`:''}${p.penalties!=null?`${p.pim!=null?' · ':''}${p.penalties} penalties`:''} on ${esc(h.latest.date)}.</p>`).join('')}<button data-ui-go313="scout">Open opponent scouting</button></section>`;
}
function renderOpponentHistory320(){const g=game31(),target=g?.opponent||$('#scoutOpponent')?.value||'',h=OP320.history(state.savedGames||[],target,g?.date||'',g?.id||'');const el=$('#opHistory320');if(!el)return;
 el.innerHTML=`<h3>Previous meetings · ${esc(target||'Choose an opponent')}</h3>${opponentReminder320(target,g?.date||'',g?.id||'')}${h.sheets.length?`${table312(['#','Player','Games on file','G','A','PTS','PIM','Penalties'],h.totals.map(p=>row312([esc(p.number),esc(p.name),p.games,...['g','a','pts','pim','penalties'].map(k=>p.known[k]?`${p[k]}${p.known[k]<p.games?' *':''}`:'—')])))}<p class="sub">Totals use ${h.sheets.length} prior scoresheet(s) for this exact opponent name. * Some games have missing stats. Players match by name and jersey number.</p>`:'<p class="sub">No earlier opponent scoresheet saved for this matchup yet.</p>'}`;
}
const priorOpen320=openWorkspace;openWorkspace=function(name){priorOpen320(name);if(name==='scout'){opponentRead320++;opponentDraft320=null;mountOpponent320();}};
const priorCommand320=renderCommand313;renderCommand313=function(){priorCommand320();if(dashboardView318!=='overview')return;const g=game31();if(g)$('#commandCenter313 .game-focus315')?.insertAdjacentHTML('afterend',opponentReminder320(g.opponent,g.date,g.id));
 const next=UI313.dashboard(state.savedGames||[],state.players,readSchedule301(),state.ratingWeights312).next;
 if(next&&(next.date!==g?.date||OP320.norm(next.opponent)!==OP320.norm(g?.opponent))){const html=opponentReminder320(next.opponent,next.date,'');if(html){const wrapper=document.createElement('div');wrapper.innerHTML=html;wrapper.querySelector('h3').textContent='Next matchup · '+next.opponent;const button=wrapper.querySelector('button');button.removeAttribute('data-ui-go313');button.onclick=()=>openNext313(next,'scout');$('#commandCenter313 .command-heading313').after(wrapper);}}
};
const rankingsPage321=document.createElement('section');rankingsPage321.className='workspace';rankingsPage321.dataset.workspacePage='opponents';document.querySelector('.app').appendChild(rankingsPage321);
sectionGroups317.find(g=>g[0]==='games')[3].push('opponents');
const rankingsButton321=document.createElement('button');rankingsButton321.type='button';rankingsButton321.dataset.workspace='opponents';rankingsButton321.textContent='Opponent rankings';rankingsButton321.onclick=()=>openWorkspace('opponents');subnav317.querySelector('[data-section317="games"]').appendChild(rankingsButton321);
let rankingsMetric321='pts',rankingsTeam321='',rankingsSearch321='',rankingsRows321=[];
function renderRankings321(){
 const data=OP320.rankings(state.savedGames||[],rankingsMetric321,rankingsTeam321,rankingsSearch321);rankingsRows321=data.rows;
 rankingsPage321.innerHTML=`<div class="workspace-page-head"><div><h1>Opponent rankings</h1><p class="sub">Every opponent player on your saved scoresheets · stats against the Foxes</p></div></div><div class="card"><div class="row"><label>Rank by <select id="opRankMetric321">${options31({pts:'Points',g:'Goals',a:'Assists',ppg:'Points per recorded game',pim:'Penalty minutes',penalties:'Penalty count'},rankingsMetric321)}</select></label><label>Team <select id="opRankTeam321"><option value="">All opponents</option>${data.teams.map(t=>`<option value="${esc(t)}" ${t===rankingsTeam321?'selected':''}>${esc(t)}</option>`).join('')}</select></label><label>Find player <input id="opRankSearch321" placeholder="Name, jersey, or team" value="${esc(rankingsSearch321)}"></label></div><p class="sub">${data.rows.length} players shown · ${data.sheets} scoresheets on file. Highest totals first; equal values share a rank. Only games with entered points count toward the points-per-game average.</p><div id="opRankTable321">${table312(['Rank','Player / Team','Games on file','G','A','PTS','PTS/game','PIM','Penalties'],data.rows.map((p,i)=>row312([p.rank??'—',`<button data-op-player321="${i}">#${esc(p.number)} ${esc(p.name)}</button><div class="sub">${esc(p.opponent)}</div>`,p.games,...['g','a','pts'].map(k=>rankValue321(p,k)),p.ppg==null?'—':p.ppg.toFixed(2)+(p.known.pts<p.games?' *':''),...['pim','penalties'].map(k=>rankValue321(p,k))])))}</div><p class="sub">— means unknown. * means some games are missing that stat; shown totals are partial. Players are matched by team, name, and jersey number.</p>${!data.sheets?'<p>Add opponent scoresheets in Games → Scout to build these rankings.</p>':''}</div><div id="opPlayerHistory321"></div>`;
 $('#opRankMetric321').onchange=e=>{rankingsMetric321=e.target.value;renderRankings321();};$('#opRankTeam321').onchange=e=>{rankingsTeam321=e.target.value;renderRankings321();};
 $('#opRankSearch321').oninput=e=>{const position=e.target.selectionStart;rankingsSearch321=e.target.value;renderRankings321();const input=$('#opRankSearch321');input.focus();input.setSelectionRange(position,position);};
 rankingsPage321.querySelectorAll('[data-op-player321]').forEach(b=>b.onclick=()=>{const p=rankingsRows321[Number(b.dataset.opPlayer321)];$('#opPlayerHistory321').innerHTML=`<section class="card"><h2>#${esc(p.number)} ${esc(p.name)} · ${esc(p.opponent)}</h2>${table312(['Game date','G','A','PTS','PIM','Penalties'],p.history.map(r=>row312([esc(r.date||'No date'),...['g','a','pts','pim','penalties'].map(k=>r[k]??'—')])))}<button id="opCloseHistory321">Close player history</button></section>`;$('#opCloseHistory321').onclick=()=>$('#opPlayerHistory321').innerHTML='';$('#opPlayerHistory321').scrollIntoView({block:'nearest'});});
}
function rankValue321(p,key){return p.known[key]?`${p[key]}${p.known[key]<p.games?' *':''}`:'—';}
const priorOpen321=openWorkspace;openWorkspace=function(name){if(name!=='opponents')return priorOpen321(name);activeWorkspace='opponents';document.querySelectorAll('.workspace').forEach(el=>el.classList.toggle('active',el===rankingsPage321));renderRankings321();context313();window.scrollTo(0,0);};
mountOpponent320();renderCommand313();
