(function(root){
'use strict';
function parseClock(text){const matches=String(text||'').match(/\b\d{1,2}:\d{2}\b/g)||[];if(matches.length!==1)return null;const [m,s]=matches[0].split(':').map(Number);return s<60?m*60+s:null;}
class Watcher{
 constructor(){this.reset();}
 reset(){this.last=null;this.running=false;this.stopped=null;this.sameSince=null;}
 sample(text,time){const value=parseClock(text);if(value===null||!Number.isFinite(time)){this.reset();return null;}const old=this.last;this.last={value,time};if(!old)return null;const dt=time-old.time,delta=old.value-value;if(dt<=0||dt>6||delta<0||delta>Math.ceil(dt)+1){this.reset();this.last={value,time};return null;}
 if(delta>0){const result=this.stopped&&time-this.stopped>=3?{start:this.stopped,end:time}:null;this.running=true;this.stopped=null;this.sameSince=null;return result;}
 if(this.running){if(this.sameSince==null)this.sameSince=old.time;if(time-this.sameSince>=3)this.stopped=this.sameSince;}return null;}
}
if(typeof module==='object'&&module.exports){module.exports={parseClock,Watcher};return;}root.FoxesScoreboard={parseClock,Watcher};
const panel=document.createElement('section');panel.hidden=true;panel.innerHTML='<h3>Scoreboard clock · Preview</h3><p>Mark only the game clock in a fixed scoreboard view. Play the video to suggest breaks. Review the times before applying them.</p><button id="clockChoose419">Mark clock</button> <button id="clockWatch419">Watch clock</button><p id="clockStatus419" role="status">No clock selected.</p><canvas id="clockCrop419" style="width:100%;max-height:100px;object-fit:contain"></canvas><div id="clockSuggestions419"></div>';side316.appendChild(panel);toolNodes416.push(panel);
const button=document.createElement('button');button.textContent='Scoreboard';button.dataset.tool416='clock';quick416.appendChild(button);const prior=openTool416;openTool416=function(name){if(name!=='clock')return prior(name);prior('more');toolNodes416.forEach(n=>n.hidden=n!==panel);selectedTool416='clock';$('#drawerTitle416').textContent='Scoreboard clock';quick416.querySelectorAll('[data-tool416]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));};button.onclick=()=>openTool416(selectedTool416==='clock'?null:'clock');
const dialog=document.createElement('dialog');dialog.style.maxWidth='min(1000px,95vw)';dialog.innerHTML='<h3>Mark the game clock</h3><p>Drag tightly around the clock digits, then save. Re-mark it if the camera or scoreboard moves.</p><canvas style="width:100%;touch-action:none"></canvas><button id="clockSave419">Save clock area</button> <button id="clockCancel419">Cancel</button>';wrap31.appendChild(dialog);const canvas=dialog.querySelector('canvas'),crop=$('#clockCrop419'),status=$('#clockStatus419');let frame,point,box,setupClip,watching=false,busy=false,epoch=0,lastTime=-1,context='',watcher=new Watcher();
function stop(message){watching=false;epoch++;watcher.reset();lastTime=-1;$('#clockWatch419').textContent='Watch clock';if(message)status.textContent=message;}
$('#clockChoose419').onclick=()=>{if(v314.readyState<2){status.textContent='Load a playable clip first.';return;}stop();v314.pause();setupClip=currentClipId();box=null;canvas.width=Math.min(1600,v314.videoWidth);canvas.height=canvas.width*v314.videoHeight/v314.videoWidth;const c=canvas.getContext('2d');c.drawImage(v314,0,0,canvas.width,canvas.height);frame=c.getImageData(0,0,canvas.width,canvas.height);dialog.showModal();};
const pos=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};};canvas.onpointerdown=e=>{point=pos(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!point)return;const p=pos(e);box={x:Math.min(point.x,p.x),y:Math.min(point.y,p.y),width:Math.abs(point.x-p.x),height:Math.abs(point.y-p.y)};const c=canvas.getContext('2d');c.putImageData(frame,0,0);c.strokeStyle='#77f3c7';c.lineWidth=3;c.strokeRect(box.x*canvas.width,box.y*canvas.height,box.width*canvas.width,box.height*canvas.height);};canvas.onpointerup=e=>{canvas.onpointermove(e);point=null;};canvas.onpointercancel=()=>point=null;
$('#clockCancel419').onclick=()=>dialog.close();$('#clockSave419').onclick=()=>{if(setupClip!==currentClipId()||!box||box.width<.01||box.height<.005)return;activeFilmClip().scoreboardClock={...box};save();dialog.close();status.textContent='Clock area saved. Play the video, then Watch clock.';};
$('#clockWatch419').onclick=()=>{if(watching){stop('Clock watch paused.');return;}if(!activeFilmClip()?.scoreboardClock||!root.foxesStorage?.readOpponentPhoto){status.textContent='Mark a clock in the Windows app first.';return;}watcher.reset();lastTime=-1;context=JSON.stringify([state.currentGameId,currentClipId()]);watching=true;epoch++;$('#clockWatch419').textContent='Stop watching';status.textContent='Watching while video plays. Suggestions do not change ice time.';};
function render(){const c=activeFilmClip(),list=$('#clockSuggestions419');list.innerHTML='';for(const s of c?.clockSuggestions||[]){if(s.reviewed)continue;const row=document.createElement('div');row.style.cssText='padding:12px 0;border-top:1px solid #46505d';row.innerHTML='<strong>Possible break</strong><label>Start (video seconds)<input type="number" min="0" step="0.1"></label><label>End (video seconds)<input type="number" min="0" step="0.1"></label><button>Confirm break</button> <button>Dismiss</button>';const inputs=row.querySelectorAll('input');inputs[0].value=s.start.toFixed(1);inputs[1].value=s.end.toFixed(1);const buttons=row.querySelectorAll('button');buttons[0].onclick=()=>{try{if(c!==activeFilmClip())throw Error('Return to the original clip.');const start=Number(inputs[0].value),end=Number(inputs[1].value);if(!inputs[0].value||!inputs[1].value||!Number.isFinite(start)||!Number.isFinite(end)||start<0||end<=start||end>v314.duration)throw Error('Enter valid start and end times.');if(!commit314(g=>{T314.whistle(g,{clipId:c.id,videoTime:start,paused:true});T314.whistle(g,{clipId:c.id,videoTime:end,paused:false});}))throw Error('Could not apply this break. Check existing whistles.');const fresh=activeFilmClip().clockSuggestions.find(x=>x.id===s.id);fresh.reviewed='confirmed';save();render();refreshWhistle416();}catch(e){status.textContent=e.message;}};buttons[1].onclick=()=>{s.reviewed='dismissed';save();render();};list.appendChild(row);}}
async function sample(){if(busy)return;try{if(context!==JSON.stringify([state.currentGameId,currentClipId()])){stop();context=JSON.stringify([state.currentGameId,currentClipId()]);render();}if(!watching||busy||v314.paused||v314.seeking||v314.readyState<2||v314.currentTime-lastTime<1)return;busy=true;const token=epoch,c=activeFilmClip(),b=c.scoreboardClock,time=v314.currentTime;lastTime=time;crop.width=600;crop.height=Math.max(30,Math.min(300,600*b.height*v314.videoHeight/(b.width*v314.videoWidth)));crop.getContext('2d').drawImage(v314,b.x*v314.videoWidth,b.y*v314.videoHeight,b.width*v314.videoWidth,b.height*v314.videoHeight,0,0,crop.width,crop.height);const blob=await new Promise(r=>crop.toBlob(r,'image/png'));const result=await root.foxesStorage.readOpponentPhoto(await blob.arrayBuffer());if(token!==epoch||c!==activeFilmClip())return;const value=parseClock(result.text),suggestion=watcher.sample(result.text,time);status.textContent=value===null?'Clock unreadable. Re-mark it if the view moved.':`Clock: ${Math.floor(value/60)}:${String(value%60).padStart(2,'0')} · Suggestions only`;if(suggestion){c.clockSuggestions=c.clockSuggestions||[];if(!c.clockSuggestions.some(s=>Math.abs(s.start-suggestion.start)<3)){c.clockSuggestions.push({id:crypto.randomUUID(),...suggestion});save();render();status.textContent='Possible break found. Check the video times below.';}}}catch(e){watcher.reset();status.textContent=e.message;}finally{busy=false;}}
v314.addEventListener('seeking',()=>{epoch++;watcher.reset();lastTime=-1;});v314.addEventListener('pause',()=>{epoch++;watcher.reset();lastTime=-1;});v314.addEventListener('loadedmetadata',()=>{stop('Clip changed. Mark or check its clock area.');render();});setInterval(sample,1000);render();
})(globalThis);
