const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../command-model'),S=require('../stats-import'),A=require('../analytics'),T=require('../toi-engine');
const roster=[{id:'a',number:16,name:'Eli Tigano',pos:'F',shifts:[]},{id:'b',number:35,name:'Hudson Bouchard',pos:'G',shifts:[]}];
test('multi-section import previews team and periods without writes and recomputes rates',()=>{
 const rows=[['#','Player','GP','G','A','S','S%','PIM'],[16,'Eli Tigano',1,1,0,2,'#DIV/0!',1.5],['#','Player','GP','MIN','S','GA','S%','GAA'],[35,'Hudson Bouchard',1,39,21,4,'#DIV/0!','#DIV/0!'],['','Team Stats','Chances','Success','Percent'],['','Power Play',3,0,'#DIV/0!'],['','Penalty Kill',2,1],['','Face-Off',42,27],['','Scoring','1st','2nd','3rd','OT','Total'],['','Goals For',2,0,0,0,2],['','Goals Against',2,1,1,0,4],['','Shots','1st','2nd','3rd','OT','Total'],['','Shots For',4,5,6,0,15],['','Shots Against',7,9,9,0,25]];
 const base={custom:'preserved'},p=S.preview(rows,roster,base,'g');assert.deepEqual(base,{custom:'preserved'});assert.equal(p.rows.filter(r=>r.ready).length,9);const out=S.apply(p,base,roster,'g'),g={id:'g',players:roster,officialStats:out};assert.equal(out.team.goalsAgainst.p2,1);assert.equal(out.team.shotsAgainst.total,25);assert.equal(out.goalies[35].saves,21);assert.equal(A.records(g)[1].svPct,21/25);assert.equal(C.team(g).fo,27/42);assert.equal(C.team(g).pk,.5);assert.equal(out.custom,'preserved');assert.deepEqual(S.apply(S.preview(rows,roster,out,'g'),out,roster,'g').team,out.team);
});
test('partial period imports preserve blank cells and invalid team ratios are skipped',()=>{const b={team:{goalsFor:{p1:3,p2:2,total:5}}},p=S.preview([['Scoring'],['Goals For','',4],['Team Stats'],['Power Play',2,3]],roster,b,'g');const out=S.apply(p,b,roster,'g');assert.equal(out.team.goalsFor.p1,3);assert.equal(out.team.goalsFor.p2,4);assert.equal(out.team.ppSuccess,undefined);});
test('weighted season rates use attempts and last five excludes scheduled games',()=>{const games=Array.from({length:6},(_,i)=>({id:String(i),date:'2026-01-0'+(i+1),players:[],officialStats:{imported:true,team:{fo:i?2:10,fow:i?1:9,goalsFor:{total:i},goalsAgainst:{total:1}}}}));const d=C.overview([...games,{id:'future',date:'2027-01-01'}],[]);assert.equal(d.fo,14/20);assert.equal(d.last5.length,5);assert.equal(d.last5[0].id,'1');assert.equal(d.diff,null);});
test('dashboard leaders keep goalies out and require ten faceoff attempts',()=>{
 const players=[...Array.from({length:3},(_,i)=>({id:'s'+i,number:i+1,name:'Skater '+i,pos:'F',shifts:[]})),{id:'g',number:99,name:'Goalie',pos:'G',shifts:[]}];
 const game={id:'leader',date:'2026-01-01',players,officialStats:{imported:true,skaters:{1:{gp:1,pts:8,g:4,a:4,shots:10,blocks:2,fo:12,fow:9,toiMin:20},2:{gp:1,pts:7,g:3,a:4,shots:9,blocks:3,fo:2,fow:2,toiMin:18},3:{gp:1,pts:6,g:2,a:4,shots:8,blocks:4,fo:10,fow:8,toiMin:16}},goalies:{99:{gp:1,saves:30,ga:1,min:45}},team:{goalsFor:{total:4},goalsAgainst:{total:1}}}};
 const d=C.overview([game],players),sets=C.leaderSets(d.rows);
 assert.equal(sets.points[0].player.number,1);
 assert.deepEqual(sets.faceoffs.map(x=>x.player.number),[3,1]);
 assert.equal(sets.points.some(x=>x.player.pos==='G'),false);
 assert.equal(C.usage(d.rows)[0].player.number,1);
 assert.equal(C.playerTrend(d.rows.find(r=>r.p.number===1),'rating')[0].rating>0,true);
});
test('overlap counts exact units once and never joins separate clips or unconfirmed intervals',()=>{const g={id:'g',players:['a','b','c'].map((id,i)=>({id,number:i,pos:'F',shifts:[{id,toiSchema:314,ended:true,confirmed:true,startClipId:'one',endClipId:'one',videoOnTime:i*10,videoOffTime:60}]}))};assert.equal(C.overlaps(g)[0].seconds,40);g.players[2].shifts[0].startClipId='two';assert.equal(C.overlaps(g).length,0);g.players[2].shifts[0].startClipId='one';g.players[2].shifts[0].confirmed=false;assert.equal(C.overlaps(g).length,0);});
test('quality does not equate empty or unresolved TOI to completion',()=>{assert.equal(C.quality({players:roster}).ready,false);const g={players:roster,toi314:{finalizedAt:1,candidates:[{status:'review'}]}};assert.equal(C.quality(g).toi,false);assert.equal(C.quality(g).unknown,1);});
test('tracking audit records corrections while source and undo snapshots remain intact',()=>{const g={id:'g',players:structuredClone(roster),filmClips:[{id:'clip',duration:100}]};const next=T.apply(g,x=>T.transition(x,{playerId:'a',direction:'ON',videoTime:5,clipId:'clip'}));assert.equal(g.players[0].shifts.length,0);assert.equal(next.toi314.audit.length,1);assert.equal(next.toi314.audit[0].changes[0].after.videoOnTime,5);});
test('all added renderer files parse and are packaged',()=>{const p=require('../package.json');for(const name of ['command-model.js','command-ui.js','film-workspace.js']){new vm.Script(fs.readFileSync(name,'utf8'),{filename:name});assert.ok(p.build.files.includes(name));}assert.ok(p.build.files.includes('command.css'));});
test('additive notes/bookmarks survive snapshots and game switching without leaking',()=>{const state={currentGameId:'a',savedGames:[{id:'a',command31:{notes:{game:{Strengths:'a'}},bookmarks:[{time:3}]}},{id:'b'}]};const c={state,deepClone:structuredClone,game31:()=>state.savedGames.find(g=>g.id===state.currentGameId),currentGameSnapshot:()=>({id:state.currentGameId,legacy:'kept'}),loadSavedGame:id=>{state.currentGameId=id;},createSimpleGame:()=>{},renderCommand313:()=>{},renderGameHub312:()=>{}};vm.createContext(c);const text=fs.readFileSync('command-ui.js','utf8');vm.runInContext(text.slice(text.indexOf('const oldSnapshot31=')),c);assert.equal(c.currentGameSnapshot().command31.notes.game.Strengths,'a');assert.equal(c.currentGameSnapshot().legacy,'kept');c.loadSavedGame('b');assert.equal(Object.keys(c.currentGameSnapshot().command31).length,0);c.loadSavedGame('a');assert.equal(c.currentGameSnapshot().command31.bookmarks[0].time,3);});
