const {app,BrowserWindow,ipcMain}=require('electron'),path=require('path'),fs=require('fs'),assert=require('node:assert/strict');
app.setPath('userData',path.join(__dirname,'../dist/visual-check/opponent-'+Date.now()));
ipcMain.handle('test-photo',(_e,b)=>require('../opponent-ocr').recognize(b));
app.whenReady().then(async()=>{
 const source=new BrowserWindow({width:1200,height:500,show:true});
 await source.loadURL('data:text/html,'+encodeURIComponent('<body style="background:white;color:black;font:26px Arial;padding:30px"><h2>Opponent player stats</h2><table style="width:1080px;text-align:left;font:26px Arial"><tr><th>#</th><th>Player</th><th>G</th><th>A</th><th>PTS</th><th>SOG</th><th>PIM</th><th>PEN</th></tr><tr><td>12</td><td>Sam Example</td><td>2</td><td>2</td><td>4</td><td>6</td><td>4</td><td>2</td></tr><tr><td>19</td><td>Alex Sample</td><td>0</td><td>1</td><td>1</td><td>3</td><td>0</td><td>0</td></tr></table></body>'));
 await new Promise(r=>setTimeout(r,400));const png=(await source.webContents.capturePage()).toPNG();source.close();
 const w=new BrowserWindow({width:1440,height:1000,show:true,webPreferences:{preload:path.join(__dirname,'opponent-preload.cjs'),contextIsolation:true,backgroundThrottling:false}});
 await w.loadFile(path.join(__dirname,'../index.html'));await new Promise(r=>setTimeout(r,3000));
 await w.webContents.executeJavaScript("document.querySelector('#createGameDate').value='2026-08-01';document.querySelector('#createOpponent').value='Example Opponent 12U';createSimpleGame();openWorkspace('scout');window.testStatsBefore=JSON.stringify(state.officialStats);");
 await w.webContents.executeJavaScript(`readOpponentPhoto320({target:{files:[new File([Uint8Array.from(atob('${png.toString('base64')}'),c=>c.charCodeAt(0))],'sample.png',{type:'image/png'})]}})`);
 const draft=await w.webContents.executeJavaScript('JSON.stringify(opponentDraft320?.rows)');console.log('OCR draft:',draft);console.log(await w.webContents.executeJavaScript('opponentDraft320?.text'));fs.writeFileSync(path.join(__dirname,'../dist/visual-check/ocr-sample.png'),png);assert.equal(JSON.parse(draft)[0].pts,'4');assert.equal(JSON.parse(draft)[0].pim,'4');
 await w.webContents.executeJavaScript("document.querySelector('#opSave320').click();if(!game31().command31?.opponentSheet)throw Error(document.querySelector('#opStatus320').textContent);if(JSON.stringify(state.officialStats)!==testStatsBefore)throw Error('Own stats changed');document.querySelector('#createGameDate').value='2026-09-01';document.querySelector('#createOpponent').value='Example Opponent 12U';createSimpleGame();openWorkspace('home');if(!document.querySelector('.op-reminder320')?.textContent.includes('4 points'))throw Error('Missing rematch reminder');openWorkspace('scout');");
 await new Promise(r=>setTimeout(r,400));fs.writeFileSync(path.join(__dirname,'../dist/visual-check/opponent.png'),(await w.webContents.capturePage()).toPNG());
 await w.webContents.executeJavaScript("document.querySelector('[data-workspace=opponents]').click();if(activeWorkspace!=='opponents'||rankingsRows321[0].pts!==4)throw Error('Rankings navigation failed');if(document.querySelector('#opRankTable321').textContent.includes('Shots'))throw Error('Shots should not be displayed');document.querySelector('[data-op-player321]').click();if(!document.querySelector('#opPlayerHistory321').textContent.includes('Sam Example'))throw Error('History did not open');document.querySelector('#opRankMetric321').value='pim';document.querySelector('#opRankMetric321').dispatchEvent(new Event('change'));if(rankingsRows321[0].pim!==4)throw Error('Penalty sort failed');");
 await new Promise(r=>setTimeout(r,400));fs.writeFileSync(path.join(__dirname,'../dist/visual-check/opponent-rankings.png'),(await w.webContents.capturePage()).toPNG());console.log('Photo import, own-stats isolation, opponent history, rematch reminder, rankings and penalty sorting passed.');app.quit();
}).catch(e=>{console.error(e);app.exit(1)});
