const {test}=require('node:test'),assert=require('node:assert/strict'),{Tracker}=require('../player-tracker');
const zone={axis:'x',boundary:.5,x:.4,y:0,width:.2,height:1,benchLow:true};
function frame(boxes){const width=200,height=120,data=new Uint8ClampedArray(width*height*4);data.fill(245);for(const b of boxes)for(let y=b.y;y<b.y+b.height;y++)for(let x=b.x;x<b.x+b.width;x++){const i=(y*width+x)*4,v=((x-b.x)*7+(y-b.y)*11)%130;data[i]=v;data[i+1]=b.color??40;data[i+2]=180-v;data[i+3]=255;}return {data,width,height};}
const normalized=b=>({x:b.x/200,y:b.y/120,width:b.width/200,height:b.height/120});
test('manual identity follows movement and emits one crossing',()=>{const tr=new Tracker(zone);let b={x:75,y:30,width:16,height:28};tr.attach(frame([b]),{playerId:'one',box:normalized(b),onIce:false},0);let events=[];for(let i=1;i<=14;i++){b={...b,x:75+i*2};const r=tr.frame(frame([b]),i*.1);assert.deepEqual(r.lost,[]);events.push(...r.events);}assert.equal(events.length,1);assert.equal(events[0].playerId,'one');assert.equal(events[0].direction,'ON');assert.equal(tr.tracks[0].playerId,'one');});
test('video jump invalidates identities without creating shifts',()=>{const tr=new Tracker(zone),b={x:75,y:30,width:16,height:28};tr.attach(frame([b]),{playerId:'one',box:normalized(b),onIce:false},0);const r=tr.frame(frame([{...b,x:120}]),5);assert.deepEqual(r.events,[]);assert.deepEqual(r.lost,['one']);});
test('blank selection and overlapping manual labels are rejected',()=>{const tr=new Tracker(zone),b={x:75,y:30,width:16,height:28};assert.throws(()=>tr.attach(frame([]),{playerId:'one',box:normalized(b),onIce:false},0),/detail/);tr.attach(frame([b]),{playerId:'one',box:normalized(b),onIce:false},0);assert.throws(()=>tr.attach(frame([b]),{playerId:'two',box:normalized(b),onIce:false},0),/overlap/);assert.equal(tr.tracks.length,1);});
test('disappearing player stops following instead of changing names',()=>{const tr=new Tracker(zone),b={x:75,y:30,width:16,height:28};tr.attach(frame([b]),{playerId:'one',box:normalized(b),onIce:false},0);const r=tr.frame(frame([]),.1);assert.deepEqual(r.events,[]);assert.deepEqual(r.lost,['one']);assert.equal(tr.tracks[0].playerId,'one');});

test('two labeled players crossing together keep separate events',()=>{const tr=new Tracker(zone);let a={x:75,y:5,width:16,height:28},b={x:75,y:75,width:16,height:28,color:120};tr.attach(frame([a,b]),{playerId:'one',box:normalized(a),onIce:false},0);tr.attach(frame([a,b]),{playerId:'two',box:normalized(b),onIce:false},0);const events=[];for(let i=1;i<=14;i++){a={...a,x:75+i*2};b={...b,x:75+i*2};const r=tr.frame(frame([a,b]),i*.1);assert.deepEqual(r.lost,[]);events.push(...r.events);}assert.deepEqual(events.map(e=>e.playerId).sort(),['one','two']);});
test('new film scripts parse and all runtime dependencies are packaged',()=>{const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),base=path.join(__dirname,'..'),p=require('../package.json');for(const f of ['ice-time.js','player-tracker.js','film-follow-ui.js']){new vm.Script(fs.readFileSync(path.join(base,f),'utf8'),{filename:f});assert.ok(p.build.files.includes(f));}assert.ok(p.build.files.includes('film-follow.css'));});
