const {test}=require('node:test'),assert=require('node:assert/strict'),T=require('../toi-engine'),I=require('../ice-time'),A=require('../analytics');
const fixture=()=>({id:'g',filmClips:[{id:'c',duration:100},{id:'b',duration:100}],players:[{id:'p',number:'1',name:'One',pos:'F',shifts:[]},{id:'q',number:'2',name:'Two',pos:'F',shifts:[]}],officialStats:{}});
const change=(g,playerId,direction,videoTime)=>T.transition(g,{playerId,direction,videoTime,clipId:'c'});
test('whistle freezes active TOI while video advances and survives reload',()=>{let g=fixture();change(g,'p','ON',10);T.whistle(g,{clipId:'c',videoTime:20,paused:true});assert.equal(T.summary(g,30,'c')[0].total,10);g=JSON.parse(JSON.stringify(g));assert.equal(T.summary(g,40,'c')[0].total,10);T.whistle(g,{clipId:'c',videoTime:40,paused:false});change(g,'p','OFF',50);assert.equal(T.summary(g)[0].total,20);assert.equal(g.players[0].shifts[0].videoOffTime,50);assert.equal(I.seconds(g.players[0].shifts[0]),20);assert.equal(A.records(g)[0].toi,20);});
test('changes during whistle preserve who is on ice without awarding stopped time',()=>{const g=fixture();change(g,'p','ON',10);T.whistle(g,{clipId:'c',videoTime:20,paused:true});change(g,'p','OFF',25);change(g,'q','ON',27);assert.equal(T.summary(g,35,'c').find(r=>r.player.id==='q').total,0);T.whistle(g,{clipId:'c',videoTime:40,paused:false});change(g,'q','OFF',50);assert.deepEqual(T.summary(g).map(r=>r.total),[10,10]);assert.equal(g.players[1].shifts.length,1);});
test('whistle seek guards are atomic, per clip and independent of legacy stats',()=>{const g=fixture();g.players[0].shifts.push({id:'old',ended:true,startElapsed:0,endElapsed:60});const legacy=JSON.stringify(g.players[0].shifts[0]);T.whistle(g,{clipId:'c',videoTime:20,paused:true});const before=JSON.stringify(g);assert.throws(()=>T.apply(g,h=>T.whistle(h,{clipId:'c',videoTime:10,paused:false})),/follow/);assert.equal(JSON.stringify(g),before);T.transition(g,{playerId:'q',direction:'ON',videoTime:10,clipId:'b'});assert.equal(T.summary(g,30,'b').find(r=>r.player.id==='q').total,20);assert.equal(JSON.stringify(g.players[0].shifts[0]),legacy);});
test('overlapping exclusions are counted once and corrected shifts recalculate',()=>{assert.equal(I.seconds({toiSchema:314,videoOnTime:0,videoOffTime:30,ended:true,iceTimePauses:[{start:5,end:15},{start:10,end:20}]}),15);const g=fixture();change(g,'p','ON',0);T.whistle(g,{clipId:'c',videoTime:10,paused:true});T.whistle(g,{clipId:'c',videoTime:20,paused:false});change(g,'p','OFF',30);T.edit(g,{shiftId:g.players[0].shifts[0].id,playerId:'p',on:15,off:25,clipId:'c'});assert.equal(T.summary(g)[0].total,5);});

test('line-combination totals exclude the same whistle interval',()=>{const g=fixture();g.players[0].pos=g.players[1].pos='D';change(g,'p','ON',0);change(g,'q','ON',0);T.whistle(g,{clipId:'c',videoTime:10,paused:true});T.whistle(g,{clipId:'c',videoTime:20,paused:false});change(g,'p','OFF',30);change(g,'q','OFF',30);assert.equal(require('../command-model').overlaps(g)[0].seconds,20);});
